- src/vm/jvm/runtime/org/perl6/nqp/runtime/BootJavaInterop.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/SixModelObject.java
The increased visibility is a neccessity for the branch that improves JVM-Interop on Rakudo, while loading of bare .class files was just incomplete.
> Add support for loading bare .class files and increase visibility for a few BootJavaInterop fields and inner class constructors.

- src/HLL/sprintf.nqp
return zero instead and let the check for the right number of arguments
do its job later on
fixes RT #122907
> Do not try to intify a missing argument

- src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java
Instead of using a `StringBuilder` (which may need to repeatedly re-allocate its internal buffer), we allocate a character array of correct size. This improves the performance of micro-benchmarks, but the effect on setting compilation is minimal.
> (Premature) optimization of nqp::join() on JVM

- docs/ops.markdown
In the quest for documenting the return value for moarvm nqp::push some
discrepancies were discovered...
> TimToady> I guess moar is just returning the 2
> which is kinda not what I'd expect
> I don't see anywhere in nqp where the value is used, actually
> er, in nom/src I should say
> might be best to say the return value is currently undefined
> documents nqp::push return value not defined

- Configure.pl
- tools/lib/NQP/Configure.pm
Now we can use --git-reference=<path> option to tell Configure.pl do not clone corresponding repo from the web but use the reference to existing local repo. It reduces time for configuring and increases disk space.
> Add git reference option into Configure.pl

- src/vm/jvm/runtime/org/perl6/nqp/io/FileHandle.java
Fixes #224 by changing the EOF checking to use the size of the file
rather than attempting to read a character using getc(). This fixes a
problem which happens when a line ends on a multiple of 32768 bytes.
I tested this via NQP's make test, ran a spectest on Rakudo (which had several failures but none that looked related), and tested manually. I only tested on regular files on Linux.
> Fix EOF with newlines on 32k byte boundaries

- src/vm/jvm/QAST/Compiler.nqp
- src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java
Tested on Linux only with a symlink. Seems to match nqp-m's behavior for a regular symlink, a dangling symlink, regular files, and non-existent files.
> [jvm] Implement nqp::readlink

- t/nqp/19-file-ops.t
- t/nqp/78-shell.t
Clean up the automatically generated "tmp" file which is created while running the test suite.
> Unlink tmp file after tests

- src/HLL/Compiler.nqp
- src/vm/moar/HLL/Backend.nqp
[timotimo asked in `#perl6`](http://irclog.perlgeek.de/perl6/2015-04-17#i_10460782) for volunteers to try running `--profile-compile` on CORE.setting.
I should've known better, but did it anyway and it did horrible OOM things to every system I tried it on. So this change makes it not do that - it now (barely) runs with about a dozen gigabytes of virtual memory.
I've also added a way to get the raw JSON without wrapping it in the HTML GUI (that's still the default). Reasoning for this is in the commit message.
> An attempt to reduce --profile's memory usage

- src/HLL/Compiler.nqp
Removing this allows the Perl 6 REPL to function in Windows once again since the line separator is handled in rakudo/src/core/IO/Handle.pm anyway.
> Removed setting the input line separator

- tools/build/Makefile-common.in
Fix /bin/sh: C:Strawberryperlbinperl.exe: command not found errors with mingw build without (hopefully) breaking other builds.
Tested with Ubuntu Linux, Windows 7 cmd and Windows 7 x64 Native Tools Command prompt.  Ran make/nmake test for all cases with only two subtests failing in one test file in Windows 7 cmd - presumably unrelated failures in t\hll/06-sprintf.t.
Hopefully one more step in working towards a smooth mingw build of rakudo.
> Update Makefile-common.in to work with mingw

- src/HLL/Compiler.nqp
Continued statement detection in `interactive` expects that any code read in
will have had the line separator removed, which is what Linenoise (and 
presumably Readline) do. However, the fallback readline doesn't. 
This fixes that.
> Make HLL::Compiler::readline chomp

- src/HLL/Compiler.nqp
Say we want to define a class in our REPL, we might input:
> class Foo {\
* method foo {...}\
* method bar {...}\
}
Only to see
===SORRY!=== Error while compiling <unknown file>
Strange text after block (missing semicolon or comma?)
at <unknown file>:1
------> class Foo {method foo {...}⏏ method bar {...} }
expecting any of:
infix
infix stopper
postfix
statement end
statement modifier
statement modifier loop
Which is surprising, and surprises are bad.
So, after we chomp the input in `deadline`, we unchomp it if we get a continuation, which means that the compiler sees code that looks like:
class Foo {
method foo {...}
method bar {...}
}
which is legal, rather than code like `class Foo { method foo {...}method bar {...}}`, which isn't. Everybody wins.
> Retain newlines in continued code

- src/core/testing.nqp
- t/nqp/19-file-ops.t
The conversion from say("ok $_ # Skipped: …") for (…) to ok() left the
test number in what is now the test description, which rapidly went out
of sync with the real test numbers.
Instead, add an optional count parameter to skip() and use that.
> Use skip() instead of ok(1, …) in t/nqp/19-file-ops.t

- src/vm/jvm/QAST/Compiler.nqp
- src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java
Do this by setting the StringBuilder's initial capacity since we can calculate the expected value. Also throw an exception for negative values of count to match nqp-m's behavior.
> Speed up nqp::x by ~20% for large values of count on the JVM

- src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java
... unless it is a non-empty directory.
This matches the behaviour of nqp::rename on MoarVM
and it avoids errors during precompilation where an
older version should be replaced.
> Let nqp::rename replace existing target on JVM

- src/vm/moar/QAST/QASTCompilerMAST.nqp
- t/moar/04-argument-truncation.t
The code didn't take into account of the possible truncation of the
argument, we don't want to convert the default value to the type of the
register but rather to the type of the destination one.
This affects the MoarVM backend only.
Possible test vectors:
```perl6
class a { method m(int8  :$i) {$i}; }; say a.new().m(:i(42));
class a { method m(int16 :$i) {$i}; }; say a.new().m(:i(42));
class a { method m(int32 :$i) {$i}; }; say a.new().m(:i(42));
```
> Correct type conversion for default arguments.

- src/vm/moar/QAST/QASTOperationsMAST.nqp
Optimize the case where there's no else branch by not emitting a goto.
Also, remove some other code that's being generated but is actually
unreachable.
The `then` branch is effectively terminated at [1], if `$operands` is 2 then we'll never reach the code generated into the following `if` as we directly jump to the `end_lbl`.
As a rough proof of correctness I've run both the NQP and the rakudo spectests with this modification and both gave positive results.
[1] https://github.com/perl6/nqp/blob/master/src/vm/moar/QAST/QASTOperationsMAST.nqp#L832
> Simplify the compilation of 'if' switches.

- src/QRegex/P6Regex/Actions.nqp
Fix [RT #127075](https://rt.perl.org/Ticket/Display.html?id=127075)
Passes `make test` in nqp and `make spectest` in rakudo
> Properly numify non-ascii tokens in regex/grammars

- src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java
After removing this check for a SaveStackException
the special case for JVM in Rakudo's src/core/control.pm
is no longer needed.
There are no new failing tests (neither with 'make test'
for NQP nor with 'make test; make install; make spectest'
for Rakudo).
Fixes two tickets for rakudo-j:
* https://rt.perl.org/Ticket/Display.html?id=122732
* https://rt.perl.org/Ticket/Display.html?id=127967
> Throw exception instead of calling dieInternal

- src/vm/jvm/QAST/Compiler.nqp
The fix is to look only at those alternatives that have
the selector for the context we are in (I|N|S|v).
I've mainly copied the code from
src/vm/moar/QAST/QASTCompilerMAST.nqp (which works
just fine).
Fixes RT #129782, RT #126491 among others.
> Fix handling of QAST::Want on JVM

- src/vm/jvm/QAST/Compiler.nqp
There were two places where 'v' was used instead of $RT_VOID.
After changing those, we can test for void context in handling
of QAST::Want.
Fixes NPE with 'sub f { sub { say 1 } }; f()()'.
> Fix handling of QAST::Want on JVM (2)

- src/vm/moar/QAST/QASTOperationsMAST.nqp
See https://irclog.perlgeek.de/perl6-dev/2016-11-01#i_13495026 and
https://irclog.perlgeek.de/perl6-dev/2016-11-01#i_13496388
Passes `make test` in nqp and `make test spectest` in rakudo.
> Remove some unused variables+accessor methods

- src/HLL/Actions.nqp
- src/HLL/Compiler.nqp
- src/HLL/Grammar.nqp
- src/HLL/World.nqp
- src/vm/moar/QAST/QASTCompilerMAST.nqp
This will allow backtraces to report the original file and line number
instead of m-CORE.setting and its line number.
This also works in EVALs, making it easier to know which one has died.
Passes `make test`
Once this has been merged, rakudo will require https://github.com/rakudo/rakudo/pull/919
> Initial support for line directives

- src/HLL/Grammar.nqp
These are the only four pairs in Unicode that we don't have
added.
Also add a comment saying that all open/close with Ps/Pe or Pi/Pf
except for the ornate parenthesis which open/close with the
opposite because they are RTL parens.
List of the four new pairs:
⟮ ⟯
Ps U+27EE MATHEMATICAL LEFT FLATTENED PARENTHESIS
Pe U+27EF MATHEMATICAL RIGHT FLATTENED PARENTHESIS
⸤ ⸥
Ps U+2E24 BOTTOM LEFT HALF BRACKET
Pe U+2E25 BOTTOM RIGHT HALF BRACKET
⟬ ⟭
Ps U+27EC MATHEMATICAL LEFT WHITE TORTOISE SHELL BRACKET
Pe U+27ED MATHEMATICAL RIGHT WHITE TORTOISE SHELL BRACKET
⸢ ⸣
Ps U+2E22 TOP LEFT HALF BRACKET
Pe U+2E23 TOP RIGHT HALF BRACKET
⸦ ⸧
Ps U+2E26 LEFT SIDEWAYS U BRACKET
Pe U+2E27 RIGHT SIDEWAYS U BRACKET
> Add four new pairs of matched delimiters brackets/parens

- src/QRegex/P5Regex/Actions.nqp
- src/QRegex/P6Regex/Actions.nqp
So perl6 -e 'say "abca" ~~ /(a)(b)(c)$٠/' now matches.
Passes `make m-test`, also a Rakudo built with this passes `make m-spectest`.
> Handle Nd's as a backreference

- src/QRegex/P5Regex/Actions.nqp
- src/QRegex/P6Regex/Actions.nqp
- src/QRegex/P6Regex/Grammar.nqp
Passes `make m-test` and a Rakudo built with it passes `make m-spectest`.
> Handle Nd's as regex quantifiers

- src/HLL/Grammar.nqp
- src/NQP/Grammar.nqp
- src/QRegex/P5Regex/Grammar.nqp
- src/QRegex/P6Regex/Grammar.nqp
Make  `<before>`'s non-capturing.
Passes `make m-test` and a Rakudo built with it passes `make m-spectest`.
> Micro-optimize Grammars

- src/QRegex/NFA.nqp
If the meta-object is not being traced we can use the much faster NQP
op. This reduces the time needed to compile a script that just defines
50 custom operators from ~60s to ~40s.
Passes `make m-test` and a Rakudo built with it passes `make m-spectest`.
jnthn++, timotimo++, lizmat++
> Use nqp::findmethod instead of *.HOW.find_method

- src/HLL/sprintf.nqp
Passes `make m-test` and a Rakudo built with this passes `make m-spectest`.
> Support Nd's in sprintf format strings

- src/QRegex/NFA.nqp
in at least one case $ind reached far into the negatives, and
before this patch it'd just straight-up crash during debug output.
> make nfa debugger resistant to negative indents

- src/core/NQPMu.nqp
- src/core/NQPRoutine.nqp
- src/vm/moar/NQP/Ops.nqp
- src/vm/moar/QAST/QASTCompilerMAST.nqp
- src/vm/moar/QAST/QASTOperationsMAST.nqp
- src/vm/moar/QAST/QASTRegexCompilerMAST.nqp
Passes `make m-test` and a Rakudo built with it passes `make m-spectest`.
There's no reason for these to be separate commits when merged, they can be squashed.
> Intify things that cause the most mvm coerce smart numify

- t/qregex/01-qregex.t
- t/qregex/rx_backtrack
- t/qregex/rx_charclass
- t/qregex/rx_metachars
- t/qregex/rx_modifiers
- t/qregex/rx_subrules
Previously :pge<comment> would todo under all backends. This has been changed
to :any<comment>. It will also allow todoing under specific backends as well
(jvm and moar currently supported).
> Update qregex tests to allow backend specific todo's

- src/vm/moar/QAST/QASTOperationsMAST.nqp
Make the wording a bit more consistent and include relevant information
where possible. E.g., if the number of arguments to an op is wrong, say
both the number expected and received; if the type of an argument is
wrong, say both the type expected and received.
NQP passes `make m-test` and Rakudo passes `make m-spectest`.
> Make errors in QASTOperationsMAST more awesome

- src/vm/moar/QAST/QASTRegexCompilerMAST.nqp
The only remaining places in QASTRegexCompilier for MVM are used for
character ranges, which need to stay lc and uc to make character ranges
make sense.
This takes advantage of the MoarVM case insensitive string index operator,
giving us at least 1.8x speed boost doing case insensitive regex.
> [moar] Use nqp::indexic op in QASTRegexCompilier

- src/vm/moar/HLL/Backend.nqp
Change two table names: `allocators` -> `types` and `callees` -> `calls`
Use `0`s instead of `NULL`s when there's no value (unneeded carry-over from a JSON output optimization).
Rename `id` fields that refer to another table's `id` field to `<other table>_id`.
Add the necessary information to the `allocations` table such that all the functionality of the "Allocations" tab in the HTML profile can be replicated.
Change the `caller_id` and `callee_id` in the `calls` table such that it's possible to find out what
routines call a particular routine.
> Make profile sql output better

- src/HLL/Compiler.nqp
Entering an invalid option when invoking nqp or perl6 leads to an
error message being printed followed by usage instructions. In both
cases this information is written to stdout when it should have been
written to stderr. This fix solves the problem for nqp by introducing
a flag which tells the code doing the writing which fd to use.
In order to fix perl6 a separate Rakudo PR is necessary. That fix
will be dependent on this one but it won't break anything even if this
fix is reverted, it will just continue to work the way it does today.
> Fix for RT #130760

- src/vm/moar/HLL/Backend.nqp
Rename calls.callee_id to calls.id
Rename calls.caller_id to calls.parent_id
Swap the order of calls.id and calls.parent_id
Add calls.deopt_all
Remove allocations.caller_id
Rename allocations.callee_id to allocations.call_id
Rename variables in the code to match SQL renames
> Some cleanup to the SQL profile output

- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance.java
Otherwise ghost elements are left.
Fixes https://rt.perl.org/Ticket/Display.html?id=131245 for the JVM.
Previously `perl6 -e 'my @a=(1,2,3,4,5); @a.pop; @a.pop, @a[4]="hi"; say @a.join(",");'` would print `1,2,3,4,hi`, now it prints `1,2,3,,hi`.
NQP passes `make j-test` and Rakudo builds and I'm currently running a `make j-spectest`.
> Zero slot when popping an array

- src/core/NQPRoutine.nqp
This way `say Match.^methods` doesn't die with `X::Method::NotFound
exception produced no message`.
NQP passes `make m-test` and Rakudo passes `make m-spectest`.
> Add .gist method to NQPRoutine

- src/HLL/Compiler.nqp
The recent change to only generate an Exception's message when it's
gisted broke using `--ll-exception`.
> Fix no message printing when using ll-exception

- src/QRegex/P6Regex/Actions.nqp
- src/vm/jvm/QAST/Compiler.nqp
- src/vm/moar/QAST/QASTRegexCompilerMAST.nqp
Current Rakudo behavior:
| _Backtrackable atom:_ | `?` | `*` | `+` | `**` | `\|` | `\|\|` |
|--|--|--|--|--|--|--|
| *Respects default (eager backtracking) mode:* | yes | yes | yes | yes | yes | yes |
| *Respects ratchet mode:* | yes | yes | yes | yes | yes | **no** |
| *Respects atom-specific backtracking modifier:* | yes | yes | yes | yes | yes | **no** |
| *Atom-specific backmod overrides ratchet mode:* | yes | yes | yes | yes | **no** | **n/a** |
With this pull request, the behavior becomes "**yes**" for all 24 cases.
Please review carefully, because these are my first commits to nqp and my understanding of this code base is limited... 😃
I basically just copied the existing no-backtrack handling code from `method alt` to `method altseq` in both the MoarVM and JVM backend …
> Make backtracking modifiers on alternations work correctly

- src/vm/jvm/runtime/org/perl6/nqp/io/AsyncProcessHandle.java
With a user thread the following program sleeps for another 18 seconds
after saying bye:
my $proc = Proc::Async.new('sleep', '20');
my $promise = $proc.start;
sleep 2;
say 'bye';
With a daemon thread the program exits after saying bye. The child
process runs for another 18 seconds on its own. That's the behaviour
with MoarVM as well.
> [jvm] Don't wait for child when program ends

- src/HLL/World.nqp
These may be lost in the noise, but accessing dynamic variables is slow.
> Remove some @*comp_line_directives accesses

- src/QRegex/Cursor.nqp
we're already in an else block from a previous
nqp::isconcrete(self) && $!braid test
> remove unreachable code in cursor_init

- t/nqp/005-comments.t
+ test for robust =end for blocks even though misaligned with its =begin
+ test to show current state of failure with nested comment blocks
that shows parsing of code ends at the first =end comment
OR an error is thrown in other circumstances
> add new pod tests

- src/QAST/SpecialArg.nqp
- t/qast/01-qast.t
The dump_extra_node_info method of the QAST::SpecialArg role would look
up the method of the same name on the immediate parent and invoke it,
dying if that method didn't exist and could not be invoked (like when mixed-in
to QAST::Want, for instance). Modifying the behavior so that it checks
whether the there is an invokable method, and if not continue along the
parent chain until one is found or all are exhausted.
> Don't die if QAST parent doesn't have dump_extra_node_info method

- src/vm/jvm/runtime/org/perl6/nqp/io/FileHandle.java
Should help with https://github.com/rakudo/rakudo/issues/1541
There is still an issue with failing spectest for eof on Rakudo that use .read, but I think those are caused by something else.
> Fix eof detection on zero-size files

- docs/built-ins.md
- src/core/IO.nqp
- t/nqp/019-file-ops.t
changes to file "src/core/IO.nqp":
+ rename sub "spew" to "spurt" for consistency with
the rest of Perl
changes to file "t/nqp/019-file-ops.t":
+ add tests for sub "spurt"
changes to file "docs/built-ins.md":
+ change "spew" to "spurt" in subs
+ add "get" to the documented methods on a file handle
+ remove full documentation on the slurp method
on a file handle (but add it the the list
of available file handle methods)
> rename IO sub "spew" to "spurt"

- t/nqp/111-spawnprocasync.t
+ provides a partial fix for nqp GH #409 (no test for merge yet)
+ note the test for stderr on moarvm is good, but it is skipped for the
jvm because something appears to be wrong with the stderr stream
interface there
+ adds comments for the tests
+ organizes the code to be more readable
> add a test for stderr in spawnprocasync

- docs/ops.markdown
- src/vm/moar/QAST/QASTOperationsMAST.nqp
Allows a child process to get the parent process id, and thus
guess if it has become orphaned.
See: #381 
Requires: https://github.com/MoarVM/MoarVM/pull/809
> Add getppid op

- src/vm/moar/profiler/template.html
Have the code in the profiler page sort routines by InclusiveTime/ExclusiveTime
values instead of percent. Fixes subtle misordering of routines.
> Profiler Template: Sort by time Instead of Pct

- src/QRegex/P6Regex/Actions.nqp
Check that there is at least one character class before applying the
regex nodes.
When compiling the 'conj' regex node, it expects to be able to shift
off at least one child node and iterates past the end as a result.
Fixes [Rakudo Issue #1622](https://github.com/rakudo/rakudo/issues/1622)
> Rakudo Issue 1622: Fix bug with iteration of empty character class

- docs/ops.markdown
- src/vm/js/Operations.nqp
- src/vm/js/nqp-runtime/reprs.js
- src/vm/jvm/QAST/Compiler.nqp
- src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/SixModelObject.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/TypeObject.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/MultiDimArrayInstanceBase.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/P6OpaqueBaseInstance.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/P6OpaqueDelegateInstance.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_i.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_i16.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_i32.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_i8.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_n.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_s.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_u16.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_u32.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_u8.java
- src/vm/moar/QAST/QASTOperationsMAST.nqp
- t/nqp/059-nqpop.t
Exposes a lower-level means of taking positional slices.
slice(@arr, int $start_elem, int $end_elem --> @copy)
Requires this [MoarVM PR](https://github.com/MoarVM/MoarVM/pull/843)
> Expose 'slice' op in NQP (MoarVM / JVM/ JS)

- src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/SixModelObject.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/TypeObject.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/MultiDimArrayInstanceBase.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/P6OpaqueBaseInstance.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/P6OpaqueDelegateInstance.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_i.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_i16.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_i32.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_i8.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_n.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_s.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_u16.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_u32.java
- src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/VMArrayInstance_u8.java
'start' is also the name of a member variable in each of these classes,
so changing the name of the parameter in the slice methods to help
avoid confusion in the future.
See the impetus for this change [here](https://github.com/rakudo/rakudo/issues/1838#issuecomment-390346938).
This commit doesn't add or remove any functionality and can safely wait until after the 2018.05 release.
> s:global/start/beginning/ in JVM slice methods

- tools/build/gen-js-makefile.nqp
The spew sub was changed to spurt to better match Rakudo.
> Fix error in JS Makefile generation (spew)

- src/vm/moar/QAST/QASTOperationsMAST.nqp
Removing entirely superfluous decont operation included when compiling
MAST for the chain op. Not only was this decont not doing any good, but
in some scenarios it would result in error (see
[Github Issue 1886](https://github.com/rakudo/rakudo/issues/1886))
although it's unclear to me why it's sometimes a useless addition and
sometimes an explicit error.
> Rakudo Issue 1886: Remove erroneous decont op in chain compilation

- docs/ops.markdown
- src/vm/js/Operations.nqp
- src/vm/js/nqp-runtime/io.js
- src/vm/jvm/runtime/org/perl6/nqp/runtime/IOOps.java
This is the NQP component of a whole spanning the MoarVM, NQP,
and Rakudo repos.
[MoarVM](https://github.com/MoarVM/MoarVM/pull/870)
[Rakudo](https://github.com/rakudo/rakudo/pull/1897)
Changed the output of getsignals from a hash to an array with signal
names interleaved with signal values.
The purpose of this is to allow for a more consistent ordering of
signals when exposed to the HLL.
> Change getsignals output from hash to array 

- src/core/testing.nqp
This will fix #467 , which now throw an exception with
no such file or directory
at gen/moar/stage2/NQPCORE.setting:1226  (NQPCORE.setting.moarvm:)
instead of hanging.
> Add callback of nqp::spawnprocasync to catch exception

- t/nqp/019-file-ops.t
This test pass on my own macOS.
I try to look back the cases that it fails, but surprisingly those did not complain about 019-file-ops.t
strange.
> unfudge test, co #274

- src/QAST/VM.nqp
Fixes #439. I looked at the other node type's dump methods and they all
looked fine.
> Sort QAST::VM annotations when dumping them

- docs/ops.markdown
- src/vm/jvm/QAST/Compiler.nqp
- src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java
NQP builds ok and passes `make j-test` and Rakudo builds ok and passes `make j-test`.
There are some references to `nqp::jvmbootinterop` in https://github.com/perl6/nqp/blob/master/docs/jvminterop.pod, but I'm not sure how to fix them. Also not sure what to do with https://github.com/perl6/nqp/blob/master/src/vm/jvm/runtime/org/perl6/nqp/runtime/GlobalContext.java#L203-L204 and https://github.com/perl6/nqp/blob/master/src/vm/jvm/runtime/org/perl6/nqp/runtime/BootJavaInterop.java (i.e., could some more stuff be removed?).
> Remove some unused JVM interop ops

- tools/build/install-moar-runner.pl
This is a small patch that makes the NQP shell runner search the moar executable and its library folders relative to its own location.
This PR is mostly about getting feedback from other devs. I do not expect this PR (and the respective PRs in MoarVM and Rakudo) to be merged right away.
> Relocatable NQP

- .travis.yml
- src/vm/jvm/QAST/Compiler.nqp
- src/vm/jvm/runtime/org/perl6/nqp/io/AsyncProcessHandle.java
- src/vm/jvm/runtime/org/perl6/nqp/io/SyncProcessHandle.java
- src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java
- tools/build/Makefile-JVM.in
Note: Will require updating the rakudo travis config to use jdk 9 similar to the one included in this PR
JDK 9 adds a new process api:
https://docs.oracle.com/javase/9/docs/api/java/lang/ProcessHandle.html
* Renamed existing `ProcessHandle` class because I wasn't sure how it
would interact with the new java.lang.ProcessHandle.
* Adds `getppid` op on jvm using the new process api.
* Reimplements `getpid` using the new process api.
`ProcessHandle.Info` could probably be used to implement the cpu time instead of `.getOperatingSystemMXBean()`
> [jvm] Add getppid op and upgrade to jdk9

- tools/lib/NQP/Config/NQP.pm
moar backend will be implicitly chosen if moar executable found either
in --prefix or in PATH.
> Added detection of moar executable in --prefix

- src/HLL/CommandLine.nqp
- src/HLL/Compiler.nqp
- src/vm/moar/HLL/Backend.nqp
Now `--profile(-compile)=<foo>` will set the filename and
`--profile-kind=<foo>` will set whether it's an instrumented or heap
profile.
If this is merged I'll create a corresponding rakudo PR to correct its help output.
> Change default profile options

- src/QRegex/P6Regex/Grammar.nqp
- t/qregex/rx_metachars
Needed for https://github.com/rakudo/rakudo/pull/2907 to work.
> Parse |, ||, &, && prefixes not in nibble

- .gitmodules
Ownership of nqp-configure repo has been transferred to Perl6
organization.
It is recommended to run:
git submodule sync
git submodule update --init --recursive --remote
> Change URL of 3rdparty/nqp-configure submodule

- Configure.pl
- tools/lib/NQP/Config/NQP.pm
Provides better support for relocatable too.
#544
> Use moar from PATH only when no other prefix-defining options are used.

- Configure.pl
- tools/lib/NQP/Config/NQP.pm
With this PR `Configure.pl` would set git configuration variable `submodule.recurse` to true once. With this variable `git` would also auto-update all submodules if necessary upon each `pull` operation. `Configure.pl` would also set `nqp.initialized` variable to prevent repetitive changing of `submodule.recurse` on each run as this might be annoying if someone decides to reset it.
> A solution for nqp-configure submodule updates.

- tools/templates/jvm/Makefile.in
This shuts up warnings about the target being the wrong version of the
JDK and warnings about -bootclasspath being needed.
> Use --release 9 instead of -source 1.9 in the JVM's Makefile

- src/vm/js/nqp-runtime/bootstrap.js
- src/vm/js/nqp-runtime/core.js
- src/vm/js/nqp-runtime/deserialization.js
- src/vm/js/nqp-runtime/global-context.js
- src/vm/js/nqp-runtime/hll.js
- src/vm/js/nqp-runtime/runtime.js
- src/vm/js/nqp-runtime/serialization-context.js
- src/vm/js/nqp-runtime/serialization.js
- src/vm/js/nqp-runtime/sixmodel.js
This cleans up its code by encapsulating most of it in a `GlobalContextWrapper` singleton and moving all property declarations on `GlobalContext` to within its constructor rather than from other modules to avoid deoptimizations.
I'm making this a draft pullreq since this is my first time dealing with the JS VM and I want to refactor this a bit more so `GlobalContext` mutates its own properties, not the other modules.
Passes `make test`.
> [js] Refactor src/vm/js/nqp-runtime/global-context.js

- src/NQP/Grammar.nqp
- t/nqp/013-op.t
Just stumbled on this:
https://github.com/perl6/nqp/blob/7cccdb13e28b2aea7321bdef02408f842183d477/src/NQP/Grammar.nqp#L747
Exponentiation should be right-associative (like it is in Perl 6), no? The test suite passed before and passes after this PR, so I am not sure if this will have fall-out downstream. The second commit adds tests for the `**` operator which hasn't been exercised at all.
Maybe this is an instance of "if it's not (too) broken, don't fix it"?
> Change associativity of exponentiation to 'right'

- tools/templates/moar/Makefile.in
- tools/templates/windows/nqp-m-build.c
Don't use `exec()` as that's broken on windows. Directly use
`CreateProcess()`, wait for it to finish, retrieve the exit code and
exit with that ourselves.
> Fix return code of nqp build runner

- src/vm/js/const_map.nqp
- src/vm/jvm/QAST/Compiler.nqp
- src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java
- src/vm/moar/QAST/QASTOperationsMAST.nqp
MoarVM requires that the socket family be a separate parameter for
nqp::bind_sk and nqp::connect_sk from the port; update the JVM
accordingly and use the same platform-independent constants here as
in MoarVM.
Related to https://github.com/rakudo/rakudo/issues/3007
This still needs testing.
> [IP6NS Grant] Make socket family handling portable

- tools/templates/moar/Makefile.in
Continuation of the fix for #3136
Make NQP use the cinludes that MoarVM used. Pointed out by vrurg++.
> Use cincludes configuration variable from MoarVM

- src/how/NQPConcreteRoleHOW.nqp
- src/how/NQPParametricRoleHOW.nqp
Add `:transitive` parameter for method `roles`. Make the parameter optional on `NQPParametricRoleHOW`.
> Provide better compatibility with Perl6 Metamodel

- tools/templates/jvm/Makefile.in
- tools/templates/jvm/nqp-j.in
Don't send it into gen/jvm but only use the `base_dir` to keep a single
copy of it. Still, not the best solution but we keep all the jars there
anyway for now.
#589
> An attempt to fix nqp-runtime.jar dependency

- src/vm/moar/runner/main.c
Now builds clean with `--relocatable` and without.
> Fix compiler warnings in main runner

- src/QRegex/Cursor.nqp
During timtoady's cleanup of the Braid API a copy paste error made
it through. This was discovered by cognomial++ some time ago.
This commit fixes the error where the Braid grammar class attribute
should have been initialized with a grammar instance.
> Fix for https://github.com/perl6/nqp/issues/559

- Configure.pl
- tools/build/update-submodules.pl
- tools/lib/NQP/Config/NQP.pm
The option was documented but not implemented anymore. I suspect it was
lost during the great build system refactor.
This option makes the configure process create / update git repositories
for all of its submodules and MoarVM in the given folders and use those
as reference repos. The option is forwarded to a potential MoarVM
sub-build.
> Implement `--git-reference` Configure.pl option

- tools/templates/Makefile-backend-common.in
- tools/templates/Makefile.in
This also fixes broken parallel compilation. So, `.NOTPARALLEL` isn't
needed anymore.
> Add a missing dependency

- src/HLL/CommandLine.nqp
Fix: rakudo/rakudo#1464 <- prettify error message when 2 `--target` argument are provided
With a try catch, catching an impossible stringification of `%attribute<target>`
```sh
./install/bin/perl6 --target=parse --target=ast  < /dev/null
```
```text
Unhandled exception: cannot stringify this
at gen/moar/stage2/NQPHLL.nqp:547  (/usr/share/nqp/lib/NQPHLL.moarvm:is_precomp_stage)
from gen/moar/stage2/NQPHLL.nqp:1752  (/usr/share/nqp/lib/NQPHLL.moarvm:command_line)
from gen/moar/main.nqp:54  (/usr/lib/perl6/runtime/perl6.moarvm:MAIN)
from gen/moar/main.nqp:42  (/usr/lib/perl6/runtime/perl6.moarvm:<mainline>)
from <unknown>:1  (/usr/lib/perl6/runtime/perl6.moarvm:<main>)
from <unknown>:1  (/usr/lib/perl6/runtime/perl6.moarvm:<entry>)
```
```text
Multiple --target argument not allowed. Please …
```
> More explicit error when more than one --target is provided (issue #600)

- src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java
This helps with a couple of spectests that die in core.c/Backtrace.pm6, in
https://github.com/rakudo/rakudo/blob/9429728cbd/src/core.c/Backtrace.pm6#L107
The code tries to mimic the behaviour of MoarVM, esp.
https://github.com/MoarVM/MoarVM/blob/3c3ad0678a/src/core/exceptions.c#L555-L572
> [JVM] Always provide file and line in backtrace

- tools/build/gen-version.pl
- tools/lib/NQP/Config/NQP.pm
- tools/templates/Makefile-backend-common.in
- tools/templates/Makefile-common.in
- tools/templates/jvm/Makefile.in
- tools/templates/moar/Makefile.in
Also be more explicit about whether the nqp_home variable references the
folder (where we install to): `nqp_home`
or the static compile time override to set a different home dir:
`static_nqp_home`
The above is a requirement for an upcoming rakudo PR that fixes the `--nqp-home` Configure.pl option.
Also fix relocatability for the `nqp` executable.
> Static nqp home hll var

- docs/ops.markdown
- src/vm/jvm/QAST/Compiler.nqp
- src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java
With these removals, still able to build/test jvm backend on both NQP & Rakudo
> JVM opcode cleanup

- src/vm/jvm/QAST/Compiler.nqp
- src/vm/moar/QAST/QASTOperationsMAST.nqp
Passes 'make m-test' and 'make j-test' - this wasn't tested in rakudo, but rakudo does not refer to this opcode.
> Remove qlist opcode

- tools/templates/Makefile-backend-common.in
As has been discussed [on IRC](https://colabti.org/irclogger/irclogger_log/raku-dev?date=2020-05-04#l312) stage 2 also tests the ability of stage 1 NQP to compile itself. Thus
full rebuild of it is required.
> Make stage 2 always fully rebuild upon changes in sources

- src/QAST/BVal.nqp
- src/QAST/Block.nqp
- src/QAST/CompUnit.nqp
- src/QAST/IVal.nqp
- src/QAST/InlinePlaceholder.nqp
- src/QAST/NVal.nqp
- src/QAST/NodeList.nqp
- src/QAST/Op.nqp
- src/QAST/ParamTypeCheck.nqp
- src/QAST/Regex.nqp
- src/QAST/SVal.nqp
- src/QAST/Stmt.nqp
- src/QAST/Stmts.nqp
- src/QAST/Unquote.nqp
- src/QAST/VM.nqp
- src/QAST/Var.nqp
- src/QAST/WVal.nqp
- src/QAST/Want.nqp
since we construct objects null-initialized anyway.
the QASTNodes.moarvm file shrinks by 544 bytes (about 0.54%). Even though it's a tiny change in total, we don't have to be wasteful either.
> Don't bind an int attribute to 0 directly after construction

- src/HLL/sprintf.nqp
- t/hll/06-sprintf.t
It's already documented like this in `p6doc independent-routines`, and matches C behavior.
> Fix sprintf() with *-specified negative width argument

- src/vm/jvm/runtime/org/raku/nqp/io/AsyncServerSocketHandle.java
Before, it was passing the server's port, not the connection's port.
> [jvm] Pass correct connection port in nqp::asynclisten

- t/nqp/114-pod-panic.t
This change fixes t/nqp/114-pod-panic with a relocated `nqp` executable. There was some custom logic to determine the executable name to test with. I'm unsure if there was a deeper reason for the previous more complex logic. Let's see what CI has to say.
> Fix t/nqp/114-pod-panic with a relocated `nqp` executable

- .gitmodules
- README.pod
- docs/6model/faq.markdown
- docs/6model/overview.markdown
- docs/6model/repr-compose-protocol.markdown
- docs/continuations.pod
- docs/jvminterop-goals.pod
- docs/release_guide.pod
- examples/hello_world.nqp
- package.json
- src/how/NQPClassHOW.nqp
+ Perl6 to raku
+ fix the link for travis-ci
+ format README.pod
+ change Perl6 references to Raku in docs
+ remove redundant link https://rakudo.perl6.org/downloads/nqp/: in release_guide.pod
+ reflect correct repository of NQP to http://github.com/Raku/nqp/
+ add link to irc channel making it easy to go to the channel
> Perl6 to raku + fix links

- src/HLL/Compiler.nqp
- src/vm/moar/HLL/Backend.nqp
- tools/templates/jvm/nqp-j.in
- tools/templates/jvm/nqp-j.windows
Now that nqp and rakudo are relocatable we must not rely on a build time
path. The $NQP_HOME variable is the mechanism to retrieve the actual
runtime path.
This does *not* work yet. The $NQP_HOME variable is not yet set in NQP.
> Fix retrieving template.html location

- src/HLL/Compiler.nqp
So one can still influence the NQP home even with non-relocatable NQP
builds.
> NQP_HOME env var should override a static NQP home

- src/HLL/Compiler.nqp
- src/vm/moar/HLL/Backend.nqp
This allows the code in NQP to use functionality in the HLL Compiler.
Before that wasn't possible as it wasn't known which name the subclassed
Compiler object would have.
Use that generic name to access it from NQP code. In particular in the
logic that writes the `--profile` output.
This fixes rakudo/rakudo#3824
This is has received close to no testing. (But a simple `raku --profile -e "say 'hi'"` did work.) Also I don't know if it's a good way to expose the HLL::Compiler object in this way.
> Register a plain HLL::Compiler object under the 'default' name

- src/HLL/Compiler.nqp
- tools/build/gen-jvm-properties.pl
This key is available on the other backends, and there are a couple
of special cases in Rakudo's code base because the operating system
name had to be taken from nqp::jvmgetproperties(){'os.name'}.
> [JVM] Make osname available in nqp::backendconfig

- src/how/NQPClassHOW.nqp
If a `NQPClassHOW` class get a Raku role mixin then typechecking fails
for complex cases like parameterized roles. By incorporating
`role_typecheck_list` provided by role's HOW we fix the problem.
NQP, Rakudo, and roast tests are passing.
> Support for typechecking against Raku roles

- src/HLL/Compiler.nqp
- src/vm/jvm/QAST/Compiler.nqp
- src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java
This is a bit hacky, but it should enable us to use nqp::execname
in Rakudo's code base uniformly on all backends.
Currently we use nqp::jvmgetproperties(){nqp.execname} for NQP
and nqp::jvmgetproperties(){perl6.execname} for Rakudo.
Those properties are passed to the JVM via the runner scripts nqp-j
and rakudo-j, respectively.
I've also added support for raku.execname, so perl6.execname could
be easily removed in the future.
> [JVM] Implement op 'execname'

- src/HLL/Compiler.nqp
- src/HLL/SysConfig.nqp
- src/NQP/Compiler.nqp
- src/vm/moar/HLL/Backend.nqp
- tools/templates/Makefile-backend-common.in
- tools/templates/Makefile-common.in
This class acts as a central point where configuration information is stored. The class should only ever be accessed via `nqp::gethllsym('default', 'SysConfig')`. This then allows the class to be overridden by a subclass.
> Add a HLL::SysConfig class

- src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java
Otherwise we'd need an additional null check for the JVM backend,
while on other backends, we're just checking if nqp::execname()
gave an empty string.
> [JVM] Default to empty string in nqp::execname

- t/nqp/108-vmhash.t
In particular, this adds tests for iterators, which previously were completely untested, including the ability to delete at the current iterator position, which was never directly tested before.
It also tests exceptions thrown on iterators. I was kind of assuming that the MoarVM behaviour was considered "correct" (or "canonical" here. In particular, the slightly "interesting" behaviour that you have to advance the freshly created iterator before you can use it.
Turns out that
- JS doesn't have any exceptions implemented yet
- JVM doesn't throw exceptions before the iterator is advanced to the first element
- JVM and MoarVM differ in the text of the exception thrown when the iterator is exhausted
1. Are NQP exceptions supposed to be part of the NQP language "spec"?
2. Even if "no", for …
> More tests for NQP hash behaviour.

- src/vm/js/nqp-runtime/deserialization.js
- src/vm/js/nqp-runtime/serialization.js
nqp-JS is currently a cross-compiler, and so needs to be able to read the serialization output of MoarVM. As of Feb 2020, commit 9709537d90d61529 the MoarVM serialization format was bumped from version 22 to version 23, as it now also serializes closure names.
This broke the nqp-JS build, but it seems that no-one noticed.
This fixes the build at 2020-07 (the current release), but unfortunately additional fixes are needed for changes now made on master. (report coming soon)
With this commit atop `2020-07` I still see these test failures:
```
Test Summary Report
-------------------
t/nqp/060-bigint.t                   (Wstat: 0 Tests: 157 Failed: 2)
Failed tests:  96-97
t/nqp/100-dispatcher.t               (Wstat: 0 Tests: 16 Failed: 3)
Failed tests:  6, 10, 14
t/nqp/114-pod-panic.t …
```
> Serialization format 23 for nqp-JS

- src/HLL/Compiler.nqp
The rename of `Compiler.config()` to `Compiler.sysconfig()` failed to
rename all uses. Also the naming is a bit unfortunate, as that method does
not return the `SysConfig` object, but the build configuration. So just
give it back its old name.
This PR is the basis of an upcoming rakudo PR.
> Fix `raku -V`

- t/nqp/108-vmhash.t
Also test that nqp::iterval throws - previously we were only testing
nqp::iterkey_s, and test both on iterators before the start of iteration,
and after iteration is completed.
For many cases, MoarVM throws exceptions, but the other two backends do not.
Passes on MoarVM master, A-better-hash, JVM and the last-building JS backends.
Whilst these tests (obviously) don't *change* existing behaviour, they do implicitly change the NQP language "spec", because they change some existing behaviour from "unspecified" to "canonical", hence I think that @jnthn should say whether he's happy with this.
> Tests for iterators on empty hashes, and iterators without deleting.

- docs/6model/overview.markdown
“optional” to “optionally” under hint_for. could instead be “an optional”.
> fix typo in docs/6model/overview

- src/HLL/Compiler.nqp
- src/HLL/SysConfig.nqp
- src/NQP/Compiler.nqp
This is a support PR for [rakudo/rakudo#3913](https://github.com/rakudo/rakudo/pull/3913).
Do not merge. The PR might possibly not be needed in the end.
> Move build logic to separate method so it can be called in subclasses

- src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/VMNull.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/VMNullInstance.java
When I introduced the VMNull for the JVM backend (https://github.com/Raku/nqp/pull/605), @pmurias++ suggested to use a null singleton. I'm not sure my change matches what he aimed at, though.
> [JVM] Use singleton object for VMnull

- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/DecoderInstance.java
- t/nqp/116-streaming-decoder.t
Fixes https://github.com/Raku/nqp/issues/668
The added tests might introduce some redundancy (both, within
the new tests and in combination with the existing tests). But
each block exercises a specific functionality and shows existing
problems on the JVM backend (not covered by tests before).
> Improve streaming decoder on the JVM backend

- t/docs/opcodes.t
This results in the following three opcodes being found for
MoarVM, too:
* assign_i
* assign_n
* assign_s
> Add add_native_assign_op to keywords

- tools/templates/windows/nqp-m-build.c
I'm not entirely sure how the compiler reacts to `'\"'`. Possibly the `\`
is simply ignored. Then the code worked fine before already. But better
be clear about what happens.
Note: The file makes a trip through the templating system, which unescapes
all the double backslashes.
> Build: No need to escape " in C code

- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/VMIterInstance.java
- t/nqp/108-vmhash.t
The JVM backend now throws for certain operations on hashes in
the same way as MoarVM:
* Iterating past the end of the iterator dies with "Iteration past
end of iterator" instead of throwing a NoSuchElementException.
* Before starting to iterate and after reaching the end of the
iterator, trying to access key or value gives a sane error message.
> [JVM] Align behaviour for NQP hash to MoarVM

- t/nqp/019-file-ops.t
Similarly ctime with ctime, not mtime.
This appears to be a copy-paste thinko that dates back to when the test was
originally added in 2016 by commit 37862cd52d63eb61:
Add subsecond file time ops stat_time and lstat_time
> floating point atime should be compared with integer atime, not mtime.

- src/vm/jvm/QAST/Compiler.nqp
This helps with a long standing bug on the JVM backend:
https://github.com/rakudo/rakudo/issues/3634
If last/next/redo were called within an extra block (marked as
'immediate' or 'immediate_static'), that call was translated to
a direct JVM level call. In this case the produced UnwindException
never hit it's handler.
I'm not sure this is a good way to fix the problem. But at least
it points at the relevant code.
Another caveat: If last/next/redo is used with a label, we still
get an uncaught UnwindException.
> [JVM] Make gather work with last/next/redo in loop

- src/core/testing.nqp
- t/nqp/111-spawnprocasync.t
The op now takes the program name separately instead of implicitly deriving
it from the first arg.
> Adapt tests to new `nqp::spawnprocasync` semantics

- src/how/Archetypes.nqp
Exceptions can come about from these being missing at times. No need for attributes; we don't have these luxuries here.
Edit: this is premature. Need a minute to test more.
> Stub some Archetypes methods expected by Rakudo

- src/HLL/Compiler.nqp
Before this, the rakudo-m executable built in the Rakudo source
directory would die with 'Illegal operation <given flag>' for
'--debug-suspend', '--debug-port=port', '--tracing', and
'--full-cleanup'.
> Support some missing Rakudo command line flags

- docs/ops.markdown
- src/vm/js/Operations.nqp
- src/vm/js/nqp-runtime/core.js
- src/vm/jvm/QAST/Compiler.nqp
- src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java
- src/vm/moar/QAST/QASTOperationsMAST.nqp
- t/nqp/083-math.t
These hyperbolic functions are not provided directly by libc, so have to be
implemented in terms of functions which are. There's no mathematical
difference in expressing the same identities in the Rakudo setting (it's
going to dispatched as the same IEEE operations) but it's better to do it
once there instead of once per backend.
Rakudo stopped using these ops in the 2021.02 release; now now remove them
from NQP and MoarVM.
The JS implementation of sech this commit removes is curious - it's
different from the JVM implementation, MoarVM's C implementation, all the
other JS implementations I can find online, and the "textbook" definition:
sech 𝑥 = 1 / cosh 𝑥
The relevant commits don't give any clues.
However, I *believe* it to be mathematically equivalent - after a lot of
head scratching …
> Eliminate the ops sec_n, asec_n and sech_h, which are no longer used.

- src/NQP/Optimizer.nqp
E.g., `while @a { ... }` and `if @a { ... }` are now converted into
`while nqp::elems(@a) { ... }` and `if nqp::elems(@a) { ... }`.
This micro benchmark:
```raku
my @a;
my int $i := 0;
while $i++ < 10_000_000 {
nqp::push(@a, $i);
}
my $b;
my num $s := nqp::time_n;
$b := nqp::shift(@a) while @a;
say(nqp::sub_n(nqp::time_n, $s));
say($b)
```
used to take 0.08s, now it takes 0.04s.
> Optimize truth checks of arrays in whiles and ifs

- README.pod
Travis has been disabled since the beginning of January already.
Someone should also have a look at the GitHub configuration. I suspect, the hook for Travis is still active.
Ping @Altai-man. Do you have access to the GitHub permissions and could have a look?
> Remove Travis badge

- src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java
This follows https://github.com/MoarVM/MoarVM/commit/3623701173 and
should allow to unify the code for Backtrace.new between MoarVM and
JVM backend.
> [JVM] Allow nqp::backtrace with nqp:null argument

- src/vm/jvm/QAST/Compiler.nqp
For now, it's identical to 'nativecall'. The op was introduced for
MoarVM with https://github.com/Raku/nqp/commit/28e0650f1c and it is
used in Rakudo's lib/NativeCall.rakumod.
> [JVM] Add op 'nativecallinvoke'

- src/NQP/World.nqp
- src/QRegex/Cursor.nqp
- t/nqp/050-regex.t
- t/p5regex/01-p5regex.t
- t/qregex/01-qregex.t
- tools/build/process-qregex-tests
Once its use is removed from the tests, the shim and constant aren't
needed anymore.
> Finish getting rid of NQPCursor

- src/QRegex/Cursor.nqp
It's been long enough that modules should have been fixed by now.
Not entirely sure how to test this, but NQP builds ok and passes `make m-test`, Rakudo builds ok and passes `make m-test m-spectest`, and both Slang::SQL and Slang::Tuxic install ok and pass their (albeit quite limited) tests.
> Remove no longer needed $!slang override in Braid

- src/vm/moar/QAST/QASTOperationsMAST.nqp
This ability isn't used in NQP or Rakudo, and can cause confusion. E.g.,
`for nqp::split(",", "abc,def", "ghasdfi") { say($_) }` before would
print "ghasdfi", now it dies with `Arg count 3 doesn't equal required
operand count 2 for op 'split'`.
> Disallow explicity specifying op write registers

- src/HLL/sprintf.nqp
This is a small oversight introduced in Han 2019 by commit afeef2b971c28ef4:
First stab at making num use explicit
> No need to stringify the float twice in the `sprintf` implementation.

- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/VMHash.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/VMHashInstance.java
- t/serialization/01-basic.t
This reverts commit f7c396af6b3bf6f3260c4d8c7507284a86ca53dc.
It turned out that we had at least one place where we didn't check if
the storage of a VMHash was still VMHashInstance.EMPTY_MAP:
https://github.com/Raku/nqp/blob/f1469fad3d/src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/VMHash.java#L53
Since VMHashInstance.EMPTY_MAP was shared between different instances
of VMHash, putting key/value pairs into storage affected all VMHashes
that didn't get their dedicated storage, yet.
If I'm not mistaken this was the underlying reason for
my constant $foo = nqp::hash();
not working correctly in the setting on the JVM backend. It also
explains strange problems with %DEPRECATIONS suddenly (after calling
nqp::deserialize) containing key/value pairs from other objects -- as
decribed in …
> Revert "Lazy allocation of HashMap for  VMHash storage on JVM."

- src/HLL/sprintf.nqp
- tools/generate-sprintf-pow10-table.raku
The problem we have is that for floating point formatting, sprintf needs accurate powers of 10, and nqp::num_n(1e1, $exp) is a call to the libc pow() function, and **that** may not always be accurate, with the result that we generate incorrect formatting. pow() is accurate (for all positive powers) on the little endian Linux platforms I tested but on ppc64 and sparc64, `nqp::say(nqp::pow_n(10, 210))` returns `1.0000000000000001e+210` (which I think is an error of 1 bit in the last place of the mantissa) However, MinGW seems to be much worse, with errors of 4 or 5 bits.
The obvious approach would be to implement the algorithm from MoarVM's `pow_i`, but in NQP in nums:
while (exp) {
if (exp & 1)
result *= base;
exp >>= 1;
base *= base;
}
however, **this** doesn't work because floating point …
> Accurately calculate pow_n(10.0, $exp) for floating point sprintf formatting

- t/hll/06-sprintf.t
By setting up the ints to print more robust.
See https://github.com/MoarVM/MoarVM/pull/1385#issuecomment-748591561 for the analysis that lead up to this.
> Fix sprintf large int tests

- src/vm/jvm/runtime/org/raku/nqp/sixmodel/REPRRegistry.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/SerializationWriter.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/VMArray.java
There is a long standing issue with Rakudo on the JVM backend:
If one declares a native array (like 'my int @arr;') this comes
out as a non-native array after precompilation.
(Compare https://github.com/rakudo/rakudo/issues/1666.)
I think I figured out what happened: Both, native and non-native
arrays have the REPR 'VMArray'. They differ in native arrays having
a non-null REPRData in their STable. When an array is serialized, a
string representing the REPR is put into the string heap. During the
first pass of deserialization, this string is used to create a stub
object (of the given REPR). At this moment the REPRData is not yet
known -- so a plain (non-native) VMArray is created. Only during the
second pass of deserialization, the REPRData is added to the STable
(in …
> [JVM] Deserialize native arrays as such

- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/DecoderInstance.java
- t/nqp/019-file-ops.t
Add a boolean member for it (defaults to false) and set it based on the
config hash if given.
Currently only takeAllChars uses it, because that's all that was needed
to get both t/nqp/019-file-opt.t and t/nqp/116-streaming-decoder.t to
pass on Windows with the JVM backend.
This will allow us to turn back on the JVM-on-Windows NQP test job in CI, which I accidentally did in #719, so after a rebase that PR should all pass.
> Partially implement translate_newlines config in JVM backend's DecoderInstance

- src/vm/jvm/runtime/org/raku/nqp/sixmodel/REPR.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/REPRRegistry.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/SerializationWriter.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/VMArray.java
It turned out that f3dc977 doesn't really fix the usage of native
arrays in the core setting. For some reason during the compilation of
blib/CORE.d.setting.jar native array are deserialized twice.
The first time worked as expected, but since we did reset REPR.name
to VMArray, the second time went wrong just as it used to fail before
f3dc977.
Since REPR.name is also used for nqp::reprname, it seems cleaner to
leave it untouched and add a different field (vmarray_name) to REPR
instead.
> [JVM] Keep correct REPR.name for native arrays

- src/core/Hash.nqp
Exit early if there are 0 or 1 keys to sort, also pull some variable
declarations out of a loop to reduce the number of BOOTInts allocated.
> Micro-optimize the sift_down sub in sorted_keys

- src/HLL/SysConfig.nqp
The JVM has been re-bootstrapped and `nqp::execname` now works with it.
> Remove no longer needed JVM workaround

- tools/templates/Makefile-backend-common.in
- tools/templates/moar/Makefile.in
- tools/templates/moar/moar_includes
List of include directories is now provided by moar backend and respected by NQP build.
> Implement support for moar::hllincludes config variable

- src/how/NQPParametricRoleHOW.nqp
- t/nqp/056-role.t
This allows Raku parametric roles to do nqp ones (e.g. weird HOWs).
> Give NQPParametricRoleHOW a role_typecheck_list method

- t/moar/54-dispatch-qast.t
- t/qast/01-qast.t
The JVM doesn't implement nqp::dispatch, so move any tests with that to
the MoarVM tests directory.
The JVM also hasn't implemented hllize via dispatchers, so just skip
that test on the JVM.
> Make JVM tests pass after new-disp merge

- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/DecoderInstance.java
As long as we have lines of correctly encoded input, decodertakeline
is supposed to return a valid line -- even if there is invalid data
(for the given encoding) later in the input. It should die only if
it reaches the invalid input on the line it wants to return.
A concrete example of this behaviour is exercised in the method
!read-dependencies in Rakudo's CompUnit::PrecompilationUnit::File:
The precomp files we handle there have some leading lines of text,
followed by an empty line and then there is binary data.
In the method we call IO::Handle.get repeatedly -- which uses
nqp::decodertakeline under the hood. The old code needed a dirty
workaround to not explode at this point. Now the situation is
handled more correctly.
> [JVM] Deal with invalid input in decodertakeline

- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/MultiDimArrayInstance_u32.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/VMArrayInstance_u32.java
... in VMArray with 32 bit. The old code handled the 1 as a signed
integer, so that (1 << 32) just evaluated to 1.
An alternative would have been to use Integer.toUnsignedLong(i),
which is available since Java 8. We could change to those methods
in the future -- but for consistency the should be used for the
other types of VMArrays as well.
> [JVM] Fix conversion to unsigned int

- src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/NativeCallInstance.java
It is supposed to report whether the library was loaded or not. This
is a port of https://github.com/MoarVM/MoarVM/commit/1b0950e3e9 and
is needed since https://github.com/rakudo/rakudo/commit/9ef7a7e9dd.
nine++ gave the hint for the concrete implementation on the JVM.
Please note, that the usage of nqp::unbox_i($!call) in
lib/NativeCall.rakudmod don't work yet. They result in a
NullPointerException -- but that's probably a different bug. At least
the following code works now:
use nqp;
use NativeCall;
my class native_callsite is repr('NativeCall') { };
my $bar = native_callsite.new;
say nqp::unbox_i($bar);  ## 0
> [JVM] Make nqp::unbox_i on NativeCall object work

- src/HLL/Compiler.nqp
- src/vm/moar/HLL/Backend.nqp
It's been documented as existing for a long time, but seems to have
never been implemented.
We could also just remove it as an option, which would mean we'd need to remove it from the Rakudo help text (https://github.com/rakudo/rakudo/blob/master/src/Perl6/Compiler.nqp#L214)
> Implement the -o form of the --output option

- src/QAST/Node.nqp
As inferred from a stack trace from code that was doing EVAL inside
of a hyper:
````
MoarVM oops: MVM_str_hash_fetch_nocheck called with a stale hashtable pointer
at gen/moar/stage2/QASTNode.nqp:249  (.../install/share/nqp/lib/QASTNode.moarvm:unique)
from gen/moar/Optimizer.nqp:780  (.../install/share/perl6/lib/Perl6/Optimizer.moarvm:lexical_vars_to_locals)
from gen/moar/Optimizer.nqp:2397  (.../install/share/perl6/lib/Perl6/Optimizer.moarvm:visit_block)
from gen/moar/Optimizer.nqp:2316  (.../install/share/perl6/lib/Perl6/Optimizer.moarvm:optimize)
from gen/moar/Compiler.nqp:124  (.../install/share/perl6/lib/Perl6/Compiler.moarvm:optimize)
from gen/moar/stage2/NQPHLL.nqp:2217  (.../install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
````
> Fix race when checking for global uniques

- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/CPPStruct.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/CPPStructInstance.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/CStruct.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/CStructInstance.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/CUnion.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/CUnionInstance.java
... and CUnion. (At least for uint8, uint16, and uint32).
I mostly copied this from NativeCallOps.java.
> [JVM] Handle unsignedness for CStruct, CPPStruct, CUnion

- src/QRegex/NFA.nqp
- src/vm/jvm/ModuleLoader.nqp
- src/vm/jvm/QAST/Compiler.nqp
- src/vm/moar/ModuleLoader.nqp
- src/vm/moar/QAST/QASTCompilerMAST.nqp
NQP builds ok and passes `make m-test j-test` and Rakudo builds ok and passes `make m-test m-spectest`.
The one commit I'm not 100% sure about is e1d60fb534b047fdd807fc1601a3090720a2eb72. I've never seen that error happen while taking profiles, so I'm gambling that it's safe to remove the `try`.
> Remove some not-needed `try`s, or convert to `nqp::can` + the method call

- src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java
At least getlex_u_si is called in S09-typed-arrays/native-int.t and
friends after recent uintificatation of native arrays in Rakudo.
The methods behave exactly like the *_i_si versions for now.
> [JVM] Add missing methods (bind|get)lex_u_si

- src/vm/jvm/QAST/Compiler.nqp
- src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java
- src/vm/moar/QAST/QASTOperationsMAST.nqp
The op was already implemented by MoarVM, just not mapped.
> Provide op coerce_ns on MoarVM and JVM

- src/core/Hash.nqp
- t/nqp/018-associative.t
- check number of elements in hash before doing anything
- if zero, don't do anything
- if more than zero, fetch the *keys* instead of pairs
- if 1 element, we're done
- if 2 elements, swap if necessary
- if more, only *then* do the actual sort
- use decrement in condition, account for that in initialization
Should be faster because of the key fetching algorithm, and
because it doesn't fetch the keys if none are there to fetch.
> Speed up "sorted_keys" sub for < 3 elements

- src/vm/jvm/QAST/Compiler.nqp
- src/vm/moar/QAST/QASTCompilerMAST.nqp
Actually, any object in `QAST::Node.node` with methods `file`, `line`, and `orig-line` are supported.
In support of rakudo/rakudo#5117.
> Add support for RakuAST::Origin::Match

- Configure.pl
If Git is not installed and / or the `.git` folder is not present (typically a release src archive), `Configure.pl` prints error messages about failing to execute `git`. The build continues and succeeds though if all three projects (MoarVM, NQP, Rakudo) are present. This change checks for the presence of the `.git` folder (not present = release archive) and skips the (unnecessary) submodule update in that case.
> Don't error without git but all needed files are present

- src/HLL/Compiler.nqp
Beneficial for concurrent compilations.
The symbol is only available at compilation stage.
> Provide current compiler via $*HLL-COMPILER

- src/vm/jvm/QAST/Compiler.nqp
At least DISP_ONLYSTAR is referenced by Rakudo, so it makes sense to define them similarly to src/vm/moar/QAST/QASTOperationsMAST.nqp.
> [JVM] Add some constants DISP_*

- src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java
This avoids a NullPointerException in code like the following:
nqp::say(nqp::isstr(nqp::null()))
That code prints a 0 now -- which brings the behaviour of the JVM
backend in line with that of MoarVM.
> [JVM] Handle null in is(int|num|str)

- README.pod
Replace references to `master` with `main`.
https://dev.azure.com links left unchanged for now, as apparently `main` isn't currently being built there.
> Update branch references in README.pod

- src/vm/jvm/QAST/Compiler.nqp
- src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java
- t/nqp/093-oo-ops.t
These ops exist alongside `nqp::objprimspec` as storage spec-related ops on MoarVM and the JS backend (going off `git grep` at least). `nqp::objprimunsigned` would be nice to have portably for `Array::Shaped.STORE` in https://github.com/rakudo/rakudo/pull/5062, while `nqp::objprimbits` is just added for consistency's sake. Passes `make test` and a Rakudo build, but requires https://github.com/MoarVM/MoarVM/pull/1724 in order to do so.
> [JVM] Implement the objprimunsigned and objprimbits ops

- Configure.pl
On a system where some of the standard library is chopped off into modules, Configure --help would crash with the not-too-scrutible error message that perl5 gives when a module isn't installed, so i'm thinking a friendly message would be nice
> Warn about missing perl5 libs in Configure instead of just crashing

- src/HLL/Compiler.nqp
- src/NQP/Compiler.nqp
- src/QRegex/P5Regex/Compiler.nqp
- src/QRegex/P6Regex/Compiler.nqp
- src/vm/js/HLL/Backend.nqp
- src/vm/js/bin/cross-compile.nqp
- src/vm/js/bin/nqp-js.nqp
- src/vm/jvm/HLL/Backend.nqp
- src/vm/moar/HLL/Backend.nqp
This appears to have only been used by Parrot. Every other backend has their apply_transcodings function in nqp return the original input without any modifications. This change removes the apply transcodings function, and the code that called it.
> Remove unused apply_transcoding compiler function

- src/QRegex/Cursor.nqp
... with aliases. For some reasons calling &has_aliased_names fails with an external error: https://github.com/Raku/nqp/issues/808.
The special-cased code for the JVM backend mimics the checks that are otherwise done in a single conditional (which includes a call to has_aliased_names).
> [JVM] Work around error for back-references

- t/nqp/019-file-ops.t
On Windows a file can't be deleted if it is "busy", i.e. if there is an open handle to it. This start failing locally while making some IO changes in MoarVM, although I'm not sure why it hasn't always been failing.
This updates a file deletion test to close the file it is going to unlink before actually trying to unlink it.
> Close handle before unlinking

- src/QRegex/Cursor.nqp
Also fix broken shortnames "L", "M", "N", "P", "S", "Z", and "C".
This fixes R#5486 and R#5372.
> Add lookup for translating General_Category longnames

- src/vm/moar/QAST/QASTOperationsMAST.nqp
This is useful for HLLs to check the (simple) open mode of a BOOTIO. Simple here means only the ro/wo/rw part of the mode, so no information about append/truncate/etc.
> Add open mode constants

- src/HLL/Grammar.nqp
This fixes an LTA situation:
> my %h = :1k; say 1 ~ %h<k>:exists ~ 1
===SORRY!===
MVMArray: Can't pop from an empty array
Now we throw an `X::Syntax::AmbiguousAdverb` exception:
> my %h = :1k; say 1 ~ %h<k>:exists ~ 1
===SORRY!=== Error while compiling -e
Cannot determine the destination for named argument: :exists
Try placing parentheses around the desired callsite to disambiguate.
This addresses R#1378.
> Provide better feedback for ambiguous adverb usage

- src/HLL/Compiler.nqp
As a start of providing a fix for https://github.com/rakudo/rakudo/issues/3952
> Allow --repl-mode even with parameters

- src/vm/jvm/runtime/org/raku/nqp/sixmodel/SerializationReader.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/SerializationWriter.java
- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/P6Opaque.java
- t/serialization/01-basic.t
The old deserialization code gave back a Java null when it encountered a VMNull. This led to problems when compiling Rakudo's settings: Class attributes that were initialized to nqp::null ended up as NQPMu.
Fixes https://github.com/Raku/nqp/issues/828.
> [JVM] Deserialize VMNull as such

- src/HLL/Compiler.nqp
This is a first-pass at allowing for refusing to start the REPL when there is no TTY available.
However, my preferred approach would be to nuke this concept of interactive vs non-interactive and replace with the following options for 'repl-mode':
- tty
- process
- disabled
`disabled` is akin to what happens when you run `perl` or `python`, it just sits there waiting for STDIN to complete with an `<EOF>`, then runs the code. It's identical to what `non-interactive` means at the moment.
`tty` is the default and is really only presented to the user for completeness' sake.
`process` is the same as `interactive` except that it explicitly refers to the expectation that STDIN and STDOUT will *not* be TTY. This would resolve the ambiguity that occurs with this patch where `is-interactive` is only …
> Add is-interactive to HLL::Compiler

- src/vm/jvm/runtime/org/raku/nqp/sixmodel/reprs/P6Opaque.java
- t/serialization/01-basic.t
It was wrong to use nqp::isnull for this check with ba4dc47799. An attribute that has been set to nqp::null is still initialized.
> [JVM] Fix nqp::attrinited for attribute set to null

- src/vm/jvm/runtime/org/raku/nqp/runtime/ThreadContext.java
This was reduced in https://github.com/Raku/nqp/commit/f02dbe4c9b, but I'm now seeing ArrayIndexOutOfBoundsExceptions in a variety of spectests.
One evaluation that died with this error was the following (from roast's S07-slip/slip.t):
my \a = 0, ([\+] 1..*).Slip
I played a bit and that one started to pass with a size of 120. But it feels sensible to have some buffer and since I never saw this problem before, I just went for the old value.
> [JVM] Restore size of curlonglit array

- src/QAST/Block.nqp
Reduces `getattr`s during the compile of Rakudo's CORE.c by ~560m.
> Use a local for a somewhat hot class member access
