Raku/nqp

src/vm/jvm/runtime/org/perl6/nqp/sixmodel/reprs/CArrayInstance.java

JVM version of https://github.com/MoarVM/MoarVM/pull/172 ; see there for more information

Zero-fill memory allocated for CArrays

---

docs/ops.markdown
src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java

This needs https://github.com/MoarVM/MoarVM/pull/210 beforehand.

Activate previously existing windows-1252 charset support

---

src/vm/jvm/QAST/Compiler.nqp

https://github.com/perl6/nqp/commit/87d8a61a9a78da4d8873dde1017d91d7ea6bf285

Probable code typo found by coke

---

src/vm/js/nqp-runtime/io.js
src/vm/jvm/runtime/org/perl6/nqp/io/FileHandle.java

JVM version of https://github.com/MoarVM/MoarVM/pull/215
Accompanied by https://github.com/rakudo/rakudo/pull/545

Implement extended file open modes on JVM

---

src/vm/moar/QAST/QASTOperationsMAST.nqp

Wire up encoderep MoarVM op

---

src/HLL/sprintf.nqp

Handle NaN and Inf in sprintf (directives e, f, g)

---

Configure.pl
tools/build/Makefile-common.in
tools/build/install-jvm-runner.pl
tools/lib/NQP/Configure.pm

The goal is, using Perl6 on several small systems - https://github.com/rehsack/meta-jens/commit/795476f0ea1d9b2512ae2a9985a64e0616dde31e

introduce support for staging directories during build

---

README.pod

For those that would want to create some scripts or stuff.

Info on using NQP

---

src/vm/moar/QAST/QASTOperationsMAST.nqp
src/vm/parrot/QAST/Operations.nqp

see https://github.com/rakudo/rakudo/pull/587
bool should not be mapped as a int. But I am not sure how to map it too Bool

Add size_t and bool native type, bool is standard in C99

---

docs/ops.markdown
src/vm/moar/QAST/QASTOperationsMAST.nqp
t/nqp/19-file-ops.t

Add subsecond file time ops stat_time and lstat_time

---

docs/ops.markdown

Document attrinited opcode

---

README.pod

I've seen some discussion on copyright years not being important.. (blog was about content on websites). I know it's important for books, and maybe(?) software. Since nobody will think copyright has run out/70+ years old (and since/when license allows almost anything) years may not be too important..
Please to not list me as a Perl contributor :) This is my first and probably only commit.. I guess I'll have nothing more to do with Perl. [My favourite language is now Julia, it works with Perl (and maybe it does or should work with Perl 6..).

Update year, since it's there:

---

README.pod

Maybe the same should be done for Parrot? Not sure.

supress section about nqp-rx. dead since 6 years

---

src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java

fixes NPE with 'CallFrame.new.perl'

Set values for iter for ContextRef

---

Configure.pl
tools/build/Makefile-JVM.in
tools/build/install-jvm-runner.pl.in

This enables downstream to provide custom jars instead of the provided 3rd party ones.

Enable usage of custom asm.jar, asm-tree.jar, jline.jar and jna.jar

---

src/vm/moar/QAST/QASTOperationsMAST.nqp

* get rid of an extra level of closuring
* remove the completely unused :mapper argument
* move check of "ret" value out of moarop_mapper
* make return value of moarop_mapper immediately usable
in a random test program, this takes moarop_mapper frames
down from 368,016 bytes to 336,600 bytes and removes
add_core_moarop_mapping and add_hll_moarop_mapping from
the list completely (weighing 286,688 bytes and 16,008
bytes respectively)

make mappers in MASTOperations cheaper

---

docs/ops.markdown

Also re-order the Loop/Control section so it's alphabetical like the other sections.

Add some documentation for the nqp::stmts op

---

docs/ops.markdown

Proposed documentation for nqp::nativecallrefresh

---

src/vm/jvm/runtime/org/perl6/nqp/io/FileHandle.java

Adjust to behaviour of MoarVM, cmp. #310

[jvm] Make nqp::open throw if directory is passed

---

.gitignore

So it does not accidentally get committed

Add bin/ to .gitignore

---

src/vm/moar/HLL/Backend.nqp

The existing bubble sort could take over 8s one of the times it's called
with over 4k keys when profiling a Rakudo build. That's reduced to about
0.1s with the heap sort. The usual case of <10 keys is not noticeably
changed either way.

Use heap sort to sort the keys when creating JSON

---

src/vm/moar/HLL/Backend.nqp

This creates a .sql file with several CREATE TABLE statements and many
INSERT INTO statements. This has been tested with SQLite and with the
appropriate queries the results seem to match the JSON and HTML outputs.

Add SQL as an output option for profiles

---

src/QRegex/Cursor.nqp

Hopefully turning into a native will be more efficient.
Required by https://github.com/rakudo/rakudo/pull/977

Make Cursor's $!name a str

---

src/QRegex/Cursor.nqp

These are called a combined several million times when building Rakudo.
Passes `make m-test` and builds Rakudo.

Micro-optimize some commonly called methods

---

src/vm/moar/QAST/QASTCompilerMAST.nqp

Make the wording a bit more consistent and include relevant information
where possible. Similar to 513d4eb.
NQP passes `make m-test` and Rakudo passes `make m-spectest`.

Make errors in QASTCompilerMAST more awesome

---

src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java

Do the same error checks (except with different max values depending on
the limitations of the specific VM).
NQP passes `make j-test`. Rakudo passes `make t/spec/S03-operators/repeat.t`.

Align JVM x operator with MoarVM x operator

---

src/HLL/CommandLine.nqp
src/HLL/Compiler.nqp
src/HLL/Grammar.nqp
src/HLL/sprintf.nqp
src/NQP/Actions.nqp
src/NQP/Optimizer.nqp
src/QRegex/Cursor.nqp
src/how/NQPClassHOW.nqp
src/how/NQPParametricRoleHOW.nqp
src/vm/moar/HLL/Backend.nqp
src/vm/moar/QAST/QASTOperationsMAST.nqp

nqp::eqat is much faster than doing a substr+eq.
NQP passes `make m-test` and Rakudo passes `make m-spectest`.

Convert substr+eq to eqat

---

docs/built-ins.md
src/core/Regex.nqp

start new doc for built-ins; fix typo

---

src/vm/moar/QAST/QASTOperationsMAST.nqp

Requires https://github.com/MoarVM/MoarVM/pull/737.

Add the new coerce_II op as fromI_I

---

src/vm/moar/QAST/QASTOperationsMAST.nqp

This is one part in a two part fix to [Rakudo Issue 1304](https://github.com/rakudo/rakudo/issues/1304).
The Rakudo component to this fix can be found [here](https://github.com/rakudo/rakudo/pull/1375).
Modify the 'chain' op to allow the option to use the first child as the
callee. Before the name of the op served as the operator sub and the
children the operands. This modification makes it so that, if there is
no name provided to the chain, child 0 serves as the operator and
children 1 and 2 the operands.
This modification is being made to coincide with a Rakudo development
allowing negated chained ops to continue to work as chained.

Rakudo Issue 1304: Preserve operator chaining when operators negated

---

src/vm/jvm/QAST/Compiler.nqp

This is a modification to the jvm compiler allowing the 'chain' op to use the
first child as callee if the name of the op is not set.
This modification is being made to coincide with a Rakudo development
(from a little while back) allowing negated chained ops to continue to work as chained.
See <https://github.com/rakudo/rakudo/issues/1304>.

Rakudo Issue 1304: [jvm] Allow 'chain' op to use child as callee

---

src/vm/js/Operations.nqp

This is a modification to the js compiler allowing the 'chain' op to use the
first child as callee if the name of the op is not set.
This modification is being made to coincide with a Rakudo development
(from a little while back) allowing negated chained ops to continue to work as chained.
See <https://github.com/rakudo/rakudo/issues/1304>.

Rakudo Issue 1304: [js] Allow 'chain' op to use child as callee

---

docs/built-ins.md
docs/ops.markdown
src/core/IO.nqp

changes to file "docs/built-ins.md":
+ add undocumented subs
+ add undocumented methods on a file handle
changes to file "docs/ops.markdown":
+ correct and expand on some nqp subs
change to file "src/core/IO.nqp":
+ correct indent to four spaces on IO.nqp

update docs with more information

---

.travis.yml
docs/built-ins.md
src/core/testing.nqp
t/nqp/111-spawnprocasync.t
t/nqp/113-run-command.t
t/nqp/114-pod-panic.t

+ add tests for the run-command
+ add test for improved pod-panic msg
using the new sub run-command
+ fix test for spawnprocasync
+ document all testing routines in "built-ins.md"

add a new built-in sub: run-command

---

src/HLL/Compiler.nqp

Do not close STDIN it is the source of the program
Fixes https://github.com/rakudo/rakudo/issues/1824

Fix STDIN error for non-interactive REPL mode

---

src/QAST/Children.nqp

Fix stringification of Sub when using --target=ast

---

src/vm/js/Operations.nqp
src/vm/js/nqp-runtime/core.js

`getppid` was added in nodejs v9.2.0

[js] Add getppid op

---

src/vm/moar/QAST/QASTOperationsMAST.nqp

without having to go through Int, in particular.

expose coerce_in and _ni for direct int <-> num

---

src/vm/jvm/runtime/org/perl6/nqp/io/AsyncServerSocketHandle.java

Reimplement async socket introspection

---

src/HLL/sprintf.nqp

NQP builds ok and passes `make m-test`.

Add given value to (s)printf bad-directive-type error

---

docs/ops.markdown
src/vm/moar/QAST/QASTOperationsMAST.nqp

Requires https://github.com/MoarVM/MoarVM/pull/1049

Add uname opcode for MoarVM

---

tools/build/Makefile-Moar.in
tools/build/install-moar-runner.pl

Fixes perl6#528. Replaces all uses of bash with sh.

Don't use bash

---

src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java

[JVM] Don't warn about illegal reflective access

---

tools/lib/NQP/Config/NQP.pm

When neither `--backends` nor `--gen-moar` specified on the command line then choose `moar` if `moar` executable is found. Die otherwise.

Do the right thing when choosing backends

---

Configure.pl
tools/lib/NQP/Config/NQP.pm

OpenBSD build and command line options handling improvements.
rakudo/rakudo#2904

Support for the latest changes in nqp-configure

---

Configure.pl
tools/lib/NQP/Config/NQP.pm

It brought in more _cons_ than _pros_.

Remove the option of seeking for moar in PATH

---

Configure.pl

Releases already have all the necessary submodules included. Also we don't
require git to be installed to build releases. Thus don't do any submodule
checks.

Don't check for submodules in a release

---

tools/lib/NQP/Config/NQP.pm
tools/templates/Makefile-backend-common.in
tools/templates/Makefile-common.in
tools/templates/jvm/Makefile.in
tools/templates/moar/Makefile.in

Also improve support for `--force-rebuild` via pulling in the latest `nqp-configure` submodule.

Support for the new way of doing silent/verbose builds

---

Configure.pl
tools/lib/NQP/Config/NQP.pm

Configure.pl must contain only what's absolutely necessary.

Make NQP::Configure::NQP take care of jars

---

tools/templates/jvm/Makefile.in
tools/templates/jvm/nqp-j.in

De-duplication of nqp.moarvm caused non-functional runner.

Fix for broken JVM runner

---

src/vm/jvm/QAST/Compiler.nqp
src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java

Remove sayfh opcode

---

Configure.pl
README.pod
tools/build/update-submodules.pl

there are probably more that need attention, but I noticed these.

update some copyright notices

---

src/NQP/Optimizer.nqp

I don't know why this splice was originally commented out and not used,
but it works.

Simplify loop in optimizer's incorporate_inner

---

README.pod

Changed the IRC server reflecting the current usage.

IRC server changed from freenode to libera

---

README.pod

Minor README corrections

---

src/core/dispatchers.nqp

requires https://github.com/MoarVM/MoarVM/pull/1585

Dispatcher replace arg syscall

---

src/HLL/Compiler.nqp
src/vm/js/HLL/Backend.nqp
src/vm/jvm/HLL/Backend.nqp
src/vm/moar/HLL/Backend.nqp
src/vm/moar/QAST/QASTOperationsMAST.nqp

This can be used to conditionally compile backend specific code in
modules like NativeCall

New disp nativecall

---

src/vm/moar/ModuleLoader.nqp
src/vm/moar/QAST/QASTOperationsMAST.nqp

This still tried to generate the no longer existing smrt_intify op.
Replace with a proper dispatcher based implementation.
This is pretty much nqp-intify with adjustments

Fix hll_unbox of unsigned ints

---

src/vm/moar/QAST/QASTOperationsMAST.nqp

Missed in the recent unsigned work.

Register `decont_u` as an op

---

src/vm/jvm/QAST/Compiler.nqp
src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java

... which were still missing on the JVM backend.

[JVM] Add ops 'decont_u' and 'coerce_us'

---

src/how/NQPClassHOW.nqp
src/how/NQPConcreteRoleHOW.nqp
src/how/NQPCurriedRoleHOW.nqp
src/how/NQPModuleHOW.nqp
src/how/NQPNativeHOW.nqp
src/how/NQPParametricRoleHOW.nqp

It is needed to support some improvements in Raku land.

Add optional positional parameter to archetypes method

---

azure-pipelines.yml
tools/build/checkout-repos-for-test.pl

Change names and pick the checkout repos tool from Rakudo where it's been fixed already.

Adapt CI for the `main` branch

---

t/nqp/063-slurp.t

This addresses https://github.com/Raku/nqp/issues/512.

Mark t/nqp/063-slurp.t as self-referential

---

examples/rubyish/README.md

Fix typo in rubyish/README.md

---

src/vm/jvm/runtime/org/raku/nqp/io/FileHandle.java

This should make the fudged tests in roast's S32-io/lock.t pass.

[JVM] Implement shared/non-blocking file locking

---

src/vm/jvm/runtime/org/raku/nqp/runtime/Ops.java

The old code could fail with values that had a different type check mode from the type that they are checked against. A simple example is the code from https://github.com/rakudo/rakudo/issues/2714:
class C { };
role R is C { };
say R ~~ C;
That one still said False on the JVM backend, but works with this patch.
AFAICS this happened, because we kindly set the type check mode to 1 when setting up the role:
https://github.com/rakudo/rakudo/blob/55952f679a/src/Perl6/Metamodel/ParametricRoleGroupHOW.nqp#L269
But then we ignored that value, because we only looked at the type check mode of the type to check against (C).

[JVM] Look at type check mode of checked value

---

src/vm/moar/QAST/QASTCompilerMAST.nqp

If any of the section offsets overflow the 32bit offset number that we write to the file, we throw an exception.
If any frame has more than 65534 locals or lexicals, we throw an exception.
If there are more than 65534 frames, we throw an
exception as well.
Fixes https://github.com/rakudo/rakudo/issues/5733
(unless we want to make that issue about the limitation to locals and lexicals being "what fits into 16bit", and not the too-late and rather-unhelpful failure mode)

Verify some sizes in qast compiler mast
